# -*- coding: utf-8 -*-
"""EPL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eskGjNocFvNsnllSi_-BKqW7y9D3-L0A
"""

import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

!pip install python-docx

!pip install fpdf

!pip install matplotlib
!apt-get install -y texlive-latex-extra

df1 = pd.read_csv('/content/drive/MyDrive/players_raw.csv')

df1.info()

df1.head()

df1['team'].unique()

df1['team_code'].unique()

df2 = df1.loc[df1['team'] == 19]
df2.head(10)



"""1 = Arsenal, 2 = Aston Villa, 3 = Bournemouth, 4 = Brentford, 5 = Brighton, 6 = Chelsea , 7 = Crystal Palace, 8 = Everton, 9 = Fulham, 10 = Ipswich, 11 = Leicester , 12 = Liverpool , 13 = Man City , 14 = Man Utd , 15 = Newcastle , 16 = Nottingham , 17 = Southhampton , 18 = Tottenham , 19 = West Ham , 20 = Wolves"""

mapping = {1 : 'Arsenal', 2 : 'Aston Villa', 3 : 'Bournemouth', 4 : 'Brentford', 5 : 'Brighton', 6 : 'Chelsea' ,
           7 : 'Crystal Palace' , 8 : 'Everton' , 9 : 'Fulham' , 10 : 'Ipswich' , 11 : 'Leicester' , 12 : 'Liverpool' , 13 : 'Man City' ,
           14 : 'Man Utd' , 15 : 'Newcastle' , 16 : 'Nottingham' , 17 : 'Southhampton' , 18 : 'Tottenham' , 19 : 'West Ham' , 20 : 'Wolves'}

df1['Club'] = df1['team'].map(mapping)

df1.head()

df1.info()

df3 = df1.filter(['web_name', 'starts', 'Club'])
df_Arsenal = df3.loc[df3['Club'] == 'Arsenal']
df_Arsenal.head(50)

# prompt: use seaborn to chart the above result

import matplotlib.pyplot as plt
chart = sns.barplot(y='web_name',x='starts', data=df_Arsenal)
chart.set_xticklabels(chart.get_xticklabels(), rotation=90)
plt.show()

# prompt: amend the above code for the diagram to display in a descending order and interval for x-axis should be 1

import matplotlib.pyplot as plt
df_Arsenal = df_Arsenal.sort_values(by='starts', ascending=False)
chart = sns.barplot(y='web_name',x='starts', data=df_Arsenal)
chart.set_xticklabels(chart.get_xticklabels(), rotation=90)
plt.xticks(range(0, int(df_Arsenal['starts'].max())+1, 1))
plt.show()

# prompt: in the above code the x-axis labels are wrong fix it

import matplotlib.pyplot as plt
df_Arsenal = df_Arsenal.sort_values(by='starts', ascending=False)
chart = sns.barplot(y='web_name',x='starts', data=df_Arsenal, palette='rocket')

chart.set_yticklabels(chart.get_yticklabels(), fontdict={'fontfamily':'serif','fontsize':8,'fontweight':'light'})

chart.set_xticklabels(chart.get_xticklabels(), fontdict={'fontfamily':'serif','fontsize':8,'fontweight':'light','rotation':70} )
tick_values = range(int(df_Arsenal['starts'].min()), int(df_Arsenal['starts'].max())+2, 5)
plt.xticks(ticks = tick_values, labels=[f"{i}" for i in tick_values]) # Fix applied here

for i in chart.patches:
    chart.annotate(format(i.get_width(), '.0f'),
                   (i.get_x() + i.get_width(), i.get_y()),fontsize=6, color='black', xytext=(1,-5),
                   textcoords='offset points')

chart.set_xlabel('No of Games Started',fontdict={'fontfamily':'serif','fontsize':10,'fontweight':'light'})
chart.set_ylabel('Players',fontdict={'fontfamily':'serif','fontsize':10,'fontweight':'light'})
chart.set_title('Arsenal',fontdict={'fontfamily':'serif','fontsize':12,'fontweight':'light'})
sns.set_style('dark')

plt.show()

df1['Club'].unique()

df_Aston = df1.loc[df1['Club'] == 'Aston Villa']
df_Aston.head()

import matplotlib.pyplot as plt
df_Aston = df_Aston.sort_values(by='starts', ascending=False)
chart = sns.barplot(y='web_name',x='starts', data=df_Aston, palette='rocket')

chart.set_yticklabels(chart.get_yticklabels(), fontdict={'fontfamily':'serif','fontsize':8,'fontweight':'light'})

chart.set_xticklabels(chart.get_xticklabels(), fontdict={'fontfamily':'serif','fontsize':8,'fontweight':'light','rotation':70} )
tick_values = range(int(df_Aston['starts'].min()), int(df_Aston['starts'].max())+2, 5)
plt.xticks(ticks = tick_values, labels=[f"{i}" for i in tick_values]) # Fix applied here

for i in chart.patches:
    chart.annotate(format(i.get_width(), '.0f'),
                   (i.get_x() + i.get_width(), i.get_y()),fontsize=6, color='black', xytext=(1,-5),
                   textcoords='offset points')

chart.set_xlabel('No of Games Started',fontdict={'fontfamily':'serif','fontsize':10,'fontweight':'light'})
chart.set_ylabel('Players',fontdict={'fontfamily':'serif','fontsize':10,'fontweight':'light'})
chart.set_title('Aston Villa',fontdict={'fontfamily':'serif','fontsize':12,'fontweight':'light'})
sns.set_style('dark')

plt.show()

df_Aston1 = df_Aston.filter(['web_name','starts','Club'])
df_Aston1 = df_Aston1.loc[df_Aston1['Club'] == 'Aston Villa']
df_Aston1.reset_index(drop=True, inplace=True)
df_Aston1.head(40)
